### PR TITLE
Extend keyspec styles (supersedes PR #9)

### PR DESCRIPTION
**Pull request by aadcg**
This PR follows the strategy started in #9 while maintaining full backwards compatibility. 

I'll have a second look tomorrow and will notify when it'll be ready for review.

### CODE REVIEW

**Comment by Ambrevar** [comment]
I actually kind of like this.  Not perfect, but as @jmercouris mentioned in https://github.com/atlas-engineer/nkeymaps/pull/9, this generates relatively minor disruptions.

Can we come up with a better naming than `shortcut-cua`?  What about `system-name`?

**Comment by jmercouris** [comment]
Neither have I a suggestion, let us commit.

**Comment by jmercouris** [comment]
I used a merge commit instead of rebasing, it seems to be correct in this case! Hopefully I am right :-O

**Comment by Ambrevar** [comment]
Actually there is an important issue with this: now keyspecs become unportable, in particular between Darwin and non-Darwin platforms.
This means that config / code is no longer... portable!  At least not without a bunch of `#+darwin ... #-darwin`, in which case it's obviously better to use the full name instead of the shortcut.

Thoughts?

**Comment by jmercouris** [comment]
We'll address then when we support Darwin, let us first finish Electron support. No?

**Comment by jmercouris** [comment]
Let us just let it rest for now, we can iterate on it later. In my opinion we have taken *way way way* too much of a proactive approach. We need to move with alacrity and refine things as we go on.

**Comment by Ambrevar** [comment]
Let's consider this:

```lisp
(define-key ... "ctrl-a" ...)
(define-key ... "option-a" ...)
```

This snippets won't work across different systems, which is a big no-no.
This is really what nkeymaps is against.

You are not just impacting the printing  here, but also how code is written.  This is really bad practice.  If we can't reach a consensus I'll revert, because this hasn't been thought through properly.

**Comment by Ambrevar** [comment]
> We'll address then when we support Darwin, let us first finish Electron support. No?

This is nkeymaps, not Nyxt, this library is already working on Darwin and any system.

**Comment by Ambrevar** [comment]
> Indeed, but we don't force users to write their keyspecs while adhering to `system-name`

It's not forced, but it's encouraged, because that's how the bindings will be printed, so users will certainly tend to use the system-specific shortcuts, which means that unportable code will spread inevitably.  This is bad practice.

In my opinion, this far outweighs the benefits.

**Comment by Ambrevar** [comment]
About the benefits: having "familiar" way to write keybindings is really a minor thing, not a huge benefit.  Writing Lisp code is not something "familiar" in the first place, so if the users have to write the modifiers in full words, it's not a super big deal.

This problem could be fixed on the Nyxt side by having a UI that writes the keyspecs for the user.

**Comment by jmercouris** [comment]
I see your perspective, but disagree.

```
(define-key ... "ctrl-a" ...)
(define-key ... "option-a" ...)
```

being unportable is not a bug, but a feature. macOS has a different keyboard with different semantics. Users should be using `#+darwin` and `#-darwin` to handle these kinds of operations.

If you will revert, please make it support the printing of different styles so we can achieve what we want in Nyxt without resorting to string-replace operations.

**Pull request merged**
